
project_id = "mbbfcjdfdkoggherfmff"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
jwt_expiry = 3600
enable_refresh_tokens = true

[analytics]
enabled = false
port = 54327
vector_port = 54328

[realtime]
enabled = true

[functions]
enabled = true
serve_port = 54329
function_port = 54330

[functions.validate-contact]
verify_jwt = true

[functions.score-lead]
verify_jwt = true

[observability.grafana]
enabled = false
admin_password = "password"
dashboard_port = 54331
metrics_port = 54332
