
project_id = "mbbfcjdfdkoggherfmff"

[functions.fb-lead-sync]
verify_jwt = false # Allow public access for Facebook webhook

[functions.fb-ad-sync]
verify_jwt = false # Allow public access for ad library population
timeout_seconds = 120 # Increase timeout for ad syncing to 2 minutes
