// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbbfcjdfdkoggherfmff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1iYmZjamRmZGtvZ2doZXJmbWZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3Njg5MjksImV4cCI6MjA2MTM0NDkyOX0.pLzVKIRzhm613OjtaaxY7TIoi8R2rKnZAjQieGMLTbA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);